In [1]:
# Origin: Homework for week 6 of programming class
# Author: Bryan Lim
# Title: Homework 6.ipynb
# Last modified: 2016.10.21

In [2]:
A <- matrix(c(1,2,3,4), nrow=2)
B <- matrix(c(5,6,7,8), nrow=2)
A
B

[,1] [,2]
[1,]    1    3
[2,]    2    4

[,1] [,2]
[1,]    5    7
[2,]    6    8

In [3]:
det(A)
det(B)
# Both determinants are not zero

[1] -2

[1] -2

In [4]:
solve(A)
solve(B)
# Both shows the inverse

[,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5

[,1] [,2]
[1,]   -4  3.5
[2,]    3 -2.5

In [5]:
# vectorize 1
n <- 4

for(i in 1:n){
    A <- c(1:n)
}
A

B <- matrix(A, nrow=2, ncol=2)
B

[1] 1 2 3 4

[,1] [,2]
[1,]    1    3
[2,]    2    4